### ISSUE TITLE
node diff between 7.2 & 7.3

### ISSUE THREAD

**Issue by mo35** [GrinPlusPlus/GrinPlusPlus#106]
hi there 

i had no problems to launch wallet/node and sync via port forwarding up till 7.2 version , but for some unknown to me reason 7.3 is not able to receive anything back , i see requests from 3414 going out , but nothing comes back on 3415/13415 , rechecked port forwarding , tested with local fws on/off , no luck , 7.2 node works just fine , 7.3 not connecting to anything , requests from node goes out, nothing comes back

ideas ?

**Comment by DavidBurkett** [comment]
It sounds like you're mixing concepts. 3414 is for p2p. 3415 is for your wallet listener.
If your issue is just failing to connect, you're not alone. There's a number of people who have experienced similar issues in the past day or so. I'm working on a fix now, and will release a new version in the next day or so

**Comment by mo35** [comment]
thats what i wrote , p2p on 3414 goes out just fine i see bunch of connections on grin node launch , nothing comes back to node listener on 3415 :) , so its a known problem , i will let you work then , posted since not seen any mentions about issue

**Comment by DavidBurkett** [comment]
3415 is the *wallet* listener, not the *node* listener. The node listener is for connecting to the network, the wallet listener is for receiving grins.

But yes, working on a fix. Thanks for reporting the issue.

**Comment by mo35** [comment]
latest version soved issues , thanks
