### ISSUE TITLE
tor

### ISSUE THREAD

**Issue by dsdbook** [GrinPlusPlus/GrinPlusPlus#162]

**Comment by frankcoderL** [comment]
There seems to be a problem with the wallet listener on v1.2.4 on Windows10 (not tried yet on other OS). It switches about every second between "Wallet is Reachable/Wallet is not Reachable". TOR and http adress are switching between green and orange color. Downgrade to v1.2.3 resolves the issue.

**Comment by DavidBurkett** [comment]
Hi @frankcoderL,

v1.2.4 switched to using a different server for checking wallet reachability, but my tests have shown that it's a whole lot more reliable than the one used by v1.2.3. I'm a little surprised your experience differs.

We'll continue to keep an eye on this, but I recommend installing v1.2.4 again since it has important bug fixes, and I guess ignore the wallet reachability error for now until we can figure out why it's having issues for you.

**Comment by frankcoderL** [comment]
Hi @DavidBurkett,

I have seen the problem a few times on different Windows machines. And other times it works 100% perfect. Anyway it works, even when regular switching between orange and green adress status happens. The only thing that I can say is that I have never seen it happen on v1.2.3 or older releases. Thanks! Keep up the good work.

**Comment by DavidBurkett** [comment]
This issue should be fixed in v1.2.5. Feel free to reopen it if you're still having the problem.
